/**
 * HTML building blocks for the marketing visuals: page shell, Margokit logo, browser / phone frames,
 * and Google-Sheets-style mockups of every tab generated by sheets/tracker/Code.gs.
 * Each function returns an HTML string; visuals.mjs assembles them into covers, thumbnails and pins.
 */
import { COLORS as C, fmt } from './data.mjs';

export const BRAND = { lime: '#A3E635', ink: '#0F172A', bg: '#F8FAFC', line: '#E2E8F0', muted: '#64748B', limeSoft: '#F7FEE7', limeInk: '#4D7C0F' };

const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// ---------------------------------------------------------------------------
// Page shell
// ---------------------------------------------------------------------------

export function page({ w, h, body, css = '', bg = BRAND.bg }) {
  return `<!doctype html><html><head><meta charset="utf-8">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700;800&display=block" rel="stylesheet">
<style>
*{box-sizing:border-box;margin:0;padding:0}
html,body{width:${w}px;height:${h}px;overflow:hidden}
body{background:${bg};font-family:Inter,system-ui,sans-serif;color:${BRAND.ink};-webkit-font-smoothing:antialiased}
.jk{font-family:'Plus Jakarta Sans',Inter,sans-serif}
.tab{font-variant-numeric:tabular-nums}
${BASE_CSS}
${css}
</style></head><body>${body}</body></html>`;
}

// Same mark as calculator/src/app/icon.svg (inverted colors on a lime background).
export const LOGO_SVG = (size = 48, invert = false) =>
  `<svg width="${size}" height="${size}" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg"><rect width="64" height="64" rx="14" fill="${invert ? '#0F172A' : '#A3E635'}"/><path d="M16 46V18h7l9 14 9-14h7v28h-7V30l-9 13-9-13v16z" fill="${invert ? '#A3E635' : '#0F172A'}"/></svg>`;

export const logo = (size = 48, color = BRAND.ink, invert = false) =>
  `<div class="logo" style="display:flex;align-items:center;gap:${Math.round(size * 0.3)}px">${LOGO_SVG(size, invert)}<span class="jk" style="font-weight:800;font-size:${Math.round(size * 0.62)}px;letter-spacing:-0.02em;color:${color}">Margokit</span></div>`;

// ---------------------------------------------------------------------------
// Frames
// ---------------------------------------------------------------------------

export function browser(inner, { url = 'docs.google.com/spreadsheets', width, height, dark = false } = {}) {
  return `<div class="browser" style="width:${width}px;height:${height}px">
  <div class="b-bar"><span class="dot" style="background:#FF5F57"></span><span class="dot" style="background:#FEBC2E"></span><span class="dot" style="background:#28C840"></span>
  <div class="b-url">🔒 ${esc(url)}</div></div>
  <div class="b-body">${inner}</div></div>`;
}

/** Google Sheets window chrome: file title, menus, formula bar, grid area, tab bar. */
export function sheetsApp({ title, body, tabs, active, cell = 'A1', formula = '' }) {
  return `<div class="gs">
  <div class="gs-top"><div class="gs-icon"><div></div></div><div><div class="gs-title">${esc(title)} <span class="gs-star">☆</span></div>
  <div class="gs-menu">${['File', 'Edit', 'View', 'Insert', 'Format', 'Data', 'Tools', 'Extensions', 'Help'].map((m) => `<span>${m}</span>`).join('')}</div></div>
  <div class="gs-share">Share</div></div>
  <div class="gs-fx"><span class="gs-cell">${cell}</span><span class="gs-fxi">fx</span><span class="gs-fxv">${esc(formula)}</span></div>
  <div class="gs-grid">${body}</div>
  ${tabBar(tabs, active)}</div>`;
}

const TAB_COLOR = (k) => (k === 'dashboard' ? C.primary : k === 'settings' || k === 'guide' ? C.muted : k === 'pricing' ? C.primaryInk : C.ink);
export const TRACKER_TABS = ['dashboard', 'orders', 'products', 'customers', 'settings', 'guide'];
export const PACK_TABS = ['dashboard', 'orders', 'products', 'customers', 'ads', 'content', 'cash', 'budget', 'pricing', 'settings', 'guide'];

export function tabBar(tabs, active) {
  return `<div class="gs-tabs"><span class="gs-tabicon">+</span><span class="gs-tabicon">≡</span>${tabs
    .map(([k, name]) => `<span class="gs-tab${k === active ? ' on' : ''}" style="--tc:${TAB_COLOR(k)}">${esc(name)}</span>`).join('')}</div>`;
}

export function phone(inner, { width = 390, height = 800 } = {}) {
  return `<div class="phone" style="width:${width + 28}px;height:${height + 28}px"><div class="ph-screen" style="width:${width}px;height:${height}px">
  <div class="ph-status"><span>9:41</span><span class="ph-notch"></span><svg width="62" height="14" viewBox="0 0 62 14"><rect x="0" y="9" width="3.5" height="5" rx="1" fill="#0F172A"/><rect x="5.5" y="6" width="3.5" height="8" rx="1" fill="#0F172A"/><rect x="11" y="3" width="3.5" height="11" rx="1" fill="#0F172A"/><rect x="16.5" y="0" width="3.5" height="14" rx="1" fill="#0F172A"/><rect x="32" y="1" width="25" height="12" rx="3.5" fill="none" stroke="#0F172A" stroke-opacity=".4"/><rect x="34" y="3" width="19" height="8" rx="2" fill="#0F172A"/><rect x="58.5" y="5" width="2" height="4" rx="1" fill="#0F172A" fill-opacity=".4"/></svg></div>${inner}</div></div>`;
}

// ---------------------------------------------------------------------------
// Grid (spreadsheet table)
// ---------------------------------------------------------------------------

/**
 * cols: [{ h: header, w: width, letter, auto: lime header, align, cls }]
 * rows: [{ cells: [html|{v, cls, style}], bg, strike, cls }]
 */
export function grid({ cols, rows, startRow = 1, header = true, headerH = 40, rowH = 26, fill = 0, gutter = true, letters = true }) {
  const colgroup = `<colgroup>${gutter ? '<col style="width:38px">' : ''}${cols.map((c) => `<col style="width:${c.w}px">`).join('')}</colgroup>`;
  const lettersRow = letters ? `<tr class="g-letters">${gutter ? '<th class="g-corner"></th>' : ''}${cols.map((c) => `<th>${c.letter || ''}</th>`).join('')}</tr>` : '';
  let r = startRow;
  const head = header
    ? `<tr style="height:${headerH}px">${gutter ? `<td class="g-num">${r++}</td>` : ''}${cols.map((c) => `<td class="g-h ${c.auto ? 'auto' : ''}" style="text-align:${c.align === 'right' ? 'right' : 'left'}">${esc(c.h)}</td>`).join('')}</tr>`
    : '';
  const body = rows.map((row) => {
    const style = `height:${row.h || rowH}px;${row.bg ? `background:${row.bg};` : ''}`;
    const tds = cols.map((c, i) => {
      let cell = row.cells[i];
      if (cell === undefined || cell === null) cell = '';
      const o = typeof cell === 'object' ? cell : { v: cell };
      const cls = [c.cls, o.cls, c.align === 'right' ? 'r' : c.align === 'center' ? 'c' : ''].filter(Boolean).join(' ');
      return `<td class="${cls}" style="${o.style || ''}">${o.v ?? ''}</td>`;
    }).join('');
    return `<tr class="${row.strike ? 'strike ' : ''}${row.cls || ''}" style="${style}">${gutter ? `<td class="g-num">${r++}</td>` : ''}${tds}</tr>`;
  }).join('');
  const empty = Array.from({ length: fill }, () => `<tr style="height:${rowH}px">${gutter ? `<td class="g-num">${r++}</td>` : ''}${cols.map(() => '<td></td>').join('')}</tr>`).join('');
  return `<table class="g">${colgroup}${lettersRow}${head}${body}${empty}</table>`;
}

const pos = (x, f) => (x > 0 ? `<b style="color:${C.profit}">${f(x)}</b>` : x < 0 ? `<b style="color:${C.loss}">${f(x)}</b>` : f(x));
const ROW_TINT = ['#EFF6FF', '#F5F3FF', '#FFFBEB', '#F0FDF4', '#FEF2F2', '#F1F5F9'];

// ---------------------------------------------------------------------------
// Tabs
// ---------------------------------------------------------------------------

/** Orders tab. `pick` = indexes of the columns to show (input 0–16, then 17 Total, 18 Profit, 19 Margin). */
export function ordersGrid(d, { pick = [0, 1, 2, 6, 7, 8, 10, 11, 12, 13, 17, 18, 19], rows: only, fill = 0, highlightProfit = false, rowH = 26, widths = {}, letters = true } = {}) {
  const f = fmt(d.lang);
  const L = 'ABCDEFGHIJKLMNOPQRSTUV';
  const W = [95, 90, 150, 130, 110, 90, 170, 55, 90, 95, 130, 150, 110, 120, 120, 120, 180, 95, 95, 70];
  const heads = [...d.t.orders, ...d.t.ordersCalc.slice(0, 3)];
  const right = new Set([7, 8, 9, 15, 17, 18, 19]);
  const cols = pick.map((i) => ({ h: heads[i], w: widths[i] || W[i], letter: L[i], auto: i >= 17, align: right.has(i) ? 'right' : 'left', cls: highlightProfit && i === 18 ? 'hl-col' : '' }));
  const list = only ? only.map((i) => d.orders[i]) : d.orders;
  const rows = list.map((o) => {
    const vals = [f.date(o.date), o.num, o.customer, o.phone, o.city, o.country, o.product, o.qty, f.money(o.price), f.money(o.shipIn),
      o.channel, o.payment, o.status, o.carrier, o.tracking, '', '', f.money(o.total), o.profit === null ? '' : pos(o.profit, f.money), o.margin === null ? '' : f.pct0(o.margin)];
    return { cells: pick.map((i) => (i === 12 ? { v: esc(vals[i]), cls: 'status' } : i === 18 ? vals[i] : esc(vals[i]))), bg: ROW_TINT[o.st], strike: o.st === 5 };
  });
  return grid({ cols, rows, fill, rowH, letters });
}

export function customersGrid(d, { pick = [1, 2, 4, 5, 6, 7, 8, 9, 11], fill = 0, rowH = 30, focusTags = false } = {}) {
  const f = fmt(d.lang);
  const W = [140, 170, 120, 100, 85, 85, 90, 95, 110, 100, 110, 120];
  const right = new Set([4, 5, 6, 7, 8, 9]);
  const cols = pick.map((i) => ({ h: d.t.customers[i], w: W[i], letter: 'ABCDEFGHIJKL'[i], auto: true, align: right.has(i) ? 'right' : 'left' }));
  const rows = d.customers.map((c) => {
    const tag = c.tag === 'risky' ? { v: c.tagLabel, style: `background:#FEE2E2;color:${C.loss};font-weight:700` }
      : c.tag === 'loyal' ? { v: c.tagLabel, style: `background:#DCFCE7;color:${C.profit};font-weight:700` } : '';
    const vals = [esc(c.id), esc(c.name), esc(c.city), esc(c.country), c.orders, c.delivered, c.returned,
      c.deliveryRate === null ? '' : c.deliveryRate < 0.5 ? `<b style="color:${C.loss}">${f.pct0(c.deliveryRate)}</b>` : f.pct0(c.deliveryRate),
      f.money(c.spent), f.money(c.profit), f.date(c.last), tag];
    return { cells: pick.map((i) => vals[i]), cls: focusTags && !c.tag ? 'dim' : '' };
  });
  return grid({ cols, rows, fill, rowH });
}

export function productsGrid(d, { pick = [1, 3, 5, 6, 7, 9, 10, 11, 12, 14], fill = 0, rowH = 30 } = {}) {
  const f = fmt(d.lang);
  const heads = [...d.t.products, ...d.t.productsCalc];
  const W = [80, 180, 130, 100, 110, 100, 100, 110, 120, 80, 90, 120, 110, 100, 100];
  const right = new Set([3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14]);
  const cols = pick.map((i) => ({ h: heads[i], w: W[i], letter: 'ABCDEFGHIJKLMNO'[i], auto: i >= 9, align: right.has(i) ? 'right' : 'left' }));
  const rows = d.products.map((p) => {
    const st = p.stockStatus === 'out' ? { v: p.stockLabel, style: `background:#FEE2E2;color:${C.loss};font-weight:700` }
      : p.stockStatus === 'low' ? { v: p.stockLabel, style: `background:#FEF3C7;color:${C.warn};font-weight:700` }
        : { v: p.stockLabel, style: `color:${C.profit}` };
    const vals = [p.sku, esc(p.name), esc(p.category), f.money(p.cost), f.money(p.pack), f.money(p.price), p.init, p.restock, p.low, p.sold, p.inStock, st,
      f.money(p.stockValue), f.money(p.revenue), f.money(p.profit)];
    return { cells: pick.map((i) => vals[i]) };
  });
  return grid({ cols, rows, fill, rowH });
}

export function adsGrid(d, { pick = [1, 2, 3, 4, 5, 7, 9, 10, 11, 12], fill = 0, rowH = 32, hlVerdict = false } = {}) {
  const f = fmt(d.lang);
  const P = d.t.pack;
  const heads = [...P.ads, ...P.adsCalc];
  const W = [95, 115, 175, 160, 95, 110, 110, 100, 100, 70, 120, 110, 150];
  const right = new Set([4, 5, 6, 7, 8, 9, 10, 11]);
  const cols = pick.map((i) => ({ h: heads[i], w: W[i], letter: 'ABCDEFGHIJKLM'[i], auto: i >= 7, align: right.has(i) ? 'right' : 'left', cls: hlVerdict && i === 12 ? 'hl-col' : '' }));
  const rows = d.ads.map((a) => {
    const verdict = { v: a.verdict, style: a.win ? `background:#DCFCE7;color:${C.profit};font-weight:600` : `background:#FEE2E2;color:${C.loss};font-weight:600` };
    const vals = [f.date(a.date), esc(a.platform), esc(a.campaign), esc(a.product), f.money(a.spend), a.orders, '', f.money(a.revenue), f.money(a.cpa), f.roas(a.roas),
      f.money(a.perOrder), pos(a.real, f.money), verdict];
    return { cells: pick.map((i) => vals[i]) };
  });
  return grid({ cols, rows, fill, rowH });
}

export function contentGrid(d, { pick = [0, 1, 3, 5, 7, 8, 11, 14], fill = 0, rowH = 30 } = {}) {
  const f = fmt(d.lang);
  const P = d.t.pack;
  const heads = [...P.content, ...P.contentCalc];
  const W = [95, 130, 85, 330, 150, 100, 140, 80, 70, 90, 80, 110, 90, 90, 100];
  const right = new Set([7, 8, 9, 10, 11, 12, 13, 14]);
  const cols = pick.map((i) => ({ h: heads[i], w: W[i], letter: 'ABCDEFGHIJKLMNO'[i], auto: i >= 14, align: right.has(i) ? 'right' : 'left' }));
  const maxV = Math.max(...d.content.map((c) => c.views || 0));
  const stStyle = (s) => (s === 5 ? `background:#DCFCE7;color:${C.profit}` : s === 4 ? 'background:#DBEAFE;color:#1D4ED8' : s === 0 ? `background:#F1F5F9;color:${C.muted}` : `background:#FEF3C7;color:${C.warn}`);
  const rows = d.content.map((c) => {
    const t = c.views ? c.views / maxV : 0;
    // Sheets gradient #FFFFFF → #BEF264 on Views
    const mix = (a, b) => Math.round(a + (b - a) * t);
    const grad = c.views ? `background:rgb(${mix(255, 190)},${mix(255, 242)},${mix(255, 100)})` : '';
    const vals = [f.date(c.date), esc(c.platform), esc(c.format), esc(c.hook), esc(c.product), { v: esc(c.status), style: stStyle(c.st) }, '',
      { v: c.views === null ? '' : f.int(c.views), style: grad }, f.int(c.likes), f.int(c.comments), f.int(c.shares), f.int(c.saves), f.int(c.dms), f.int(c.orders),
      c.engagement === null ? '' : f.pct1(c.engagement)];
    return { cells: pick.map((i) => vals[i]), bg: c.today ? C.primarySoft : '', cls: c.today ? 'bold' : '' };
  });
  return grid({ cols, rows, fill, rowH });
}

/** Dashboard tab, at the real layout (tiles 236 px wide, charts 450 × 290). */
export function dashboard(d, { pack = false, charts = true, scale = 1, chartRows = 1 } = {}) {
  const f = fmt(d.lang);
  const t = d.t.dash;
  const cur = d.currency;
  const D = d.dash;
  const tile = (label, value, color, money) => `<div class="tile"><div class="tl">${esc(label)}${money ? ` (${cur})` : ''}</div><div class="tv" style="${color ? `color:${color}` : ''}">${value}</div></div>`;
  const sign = (x) => (x > 0 ? C.profit : x < 0 ? C.loss : '');
  let tiles = [
    tile(t.revenue, f.money(D.revenue), '', true), tile(t.profit, f.money(D.profit), sign(D.profit), true), tile(t.margin, f.pct1(D.margin)), tile(t.orders, D.orders),
    tile(t.deliveryRate, f.pct1(D.deliveryRate)), tile(t.returnRate, f.pct1(D.returnRate), D.returnRate > 0.2 ? C.loss : ''), tile(t.aov, f.money(D.aov), '', true), tile(t.transit, f.money(D.transit), '', true),
    tile(t.stockValue, f.money(D.stockValue), '', true), tile(t.alerts, D.alerts, D.alerts > 0 ? C.warn : ''), tile(t.bestChannel, esc(D.bestChannel)), tile(t.bestProduct, esc(D.bestProduct)),
  ];
  if (pack) {
    const k = d.t.pack.dash;
    const X = d.packDash;
    tiles = tiles.concat([
      tile(k.adSpend, f.money(X.adSpend), '', true), tile(k.roas, f.roas(X.roas)), tile(k.afterAds, f.money(X.afterAds), sign(X.afterAds), true), tile(k.cpa, f.money(X.cpa), '', true),
      tile(k.cashBalance, f.money(X.cashBalance), sign(X.cashBalance), true), tile(k.cashNet, f.money(X.cashNet), sign(X.cashNet), true), tile(k.posts, X.posts), tile(k.views, f.int(X.views)),
    ].map((x) => x.replace('class="tile"', 'class="tile pk"')));
  }
  const chartHtml = charts ? `<div class="charts">
    ${chartBox(t.chartMonthly, columnChart(D.monthly.map((m) => ({ label: f.monthShort(m.d), a: m.revenue, b: m.profit })), [t.revenue, t.profit], [C.ink, '#84CC16']))}
    ${chartBox(t.chartStatus, donut(D.statusCounts, ['#3B82F6', '#8B5CF6', '#F59E0B', '#16A34A', '#DC2626', '#94A3B8']))}
    ${chartRows > 1 ? chartBox(t.chartChannel, barChart(D.channelRevenue, C.ink, f)) + chartBox(t.chartTop, barChart(D.topProducts, '#84CC16', f)) : ''}
  </div>` : '';
  return `<div class="dash" style="zoom:${scale}">
    <div class="d-title">📊 ${esc(d.t.shop)} · ${esc(d.t.sheets.dashboard)}</div>
    <div class="d-sub">${esc(t.subtitle)}</div>
    <div class="d-period"><b>${esc(t.from)}</b><span class="d-date"></span><b>${esc(t.to)}</b><span class="d-date"></span><i>${esc(t.periodHint)}</i></div>
    <div class="tiles">${tiles.join('')}</div>${chartHtml}</div>`;
}

/** Axis max with 4 round steps (1, 2, 2.5, 5 × 10ⁿ). */
function niceTop(max) {
  const raw = max / 4;
  const p = 10 ** Math.floor(Math.log10(raw));
  const step = [1, 2, 2.5, 5, 10].map((m) => m * p).find((x) => x >= raw);
  return step * 4;
}

function chartBox(title, svg) {
  return `<div class="chart"><div class="ct">${esc(title)}</div>${svg}</div>`;
}

function columnChart(data, names, colors) {
  const W = 420, H = 210, pl = 34, pb = 26, pt = 8;
  const max = Math.max(...data.flatMap((x) => [x.a, x.b]), 1);
  const top = niceTop(max);
  const bw = (W - pl) / data.length;
  const y = (v) => pt + (H - pt - pb) * (1 - v / top);
  const grid = [0, 0.25, 0.5, 0.75, 1].map((g) => `<line x1="${pl}" x2="${W}" y1="${y(top * g)}" y2="${y(top * g)}" stroke="#E5E7EB"/><text x="${pl - 6}" y="${y(top * g) + 4}" text-anchor="end">${Math.round(top * g)}</text>`).join('');
  const bars = data.map((x, i) => {
    const x0 = pl + i * bw + bw * 0.18;
    const w = bw * 0.3;
    const b = (v, dx, c) => (v > 0 ? `<rect x="${x0 + dx}" y="${y(v)}" width="${w}" height="${y(0) - y(v)}" fill="${c}" rx="1.5"/>` : '');
    return b(x.a, 0, colors[0]) + b(x.b, w + 1, colors[1]) + (i % 2 === 1 ? `<text x="${x0 + w}" y="${H - 8}" text-anchor="middle">${esc(x.label)}</text>` : '');
  }).join('');
  const legend = `<g transform="translate(${W / 2 - 90},${H + 6})"><rect width="10" height="10" fill="${colors[0]}"/><text x="15" y="9">${esc(names[0])}</text><rect x="110" width="10" height="10" fill="${colors[1]}"/><text x="125" y="9">${esc(names[1])}</text></g>`;
  return `<svg class="svgc" viewBox="0 0 ${W} ${H + 22}" width="${W}" height="${H + 22}">${grid}${bars}${legend}</svg>`;
}

function donut(data, colors) {
  const total = data.reduce((s, x) => s + x.value, 0);
  const R = 82, r = 41, cx = 120, cy = 112;
  let a0 = -Math.PI / 2;
  const segs = data.map((x, i) => {
    if (!x.value) return '';
    const a1 = a0 + (x.value / total) * Math.PI * 2;
    const large = a1 - a0 > Math.PI ? 1 : 0;
    const p = (a, rr) => `${cx + rr * Math.cos(a)},${cy + rr * Math.sin(a)}`;
    const path = `<path d="M${p(a0, R)} A${R},${R} 0 ${large} 1 ${p(a1, R)} L${p(a1, r)} A${r},${r} 0 ${large} 0 ${p(a0, r)}Z" fill="${colors[i]}"/>`;
    const mid = (a0 + a1) / 2;
    const lbl = x.value / total > 0.08 ? `<text x="${cx + ((R + r) / 2) * Math.cos(mid)}" y="${cy + ((R + r) / 2) * Math.sin(mid) + 4}" text-anchor="middle" fill="#fff" font-weight="600">${Math.round((x.value / total) * 100)}%</text>` : '';
    a0 = a1;
    return path + lbl;
  }).join('');
  const legend = data.map((x, i) => `<g transform="translate(250,${46 + i * 24})"><circle cx="5" cy="5" r="5" fill="${colors[i]}"/><text x="16" y="9">${esc(x.name)}</text></g>`).join('');
  return `<svg class="svgc" viewBox="0 0 420 232" width="420" height="232">${segs}${legend}</svg>`;
}

function barChart(data, color, f) {
  const rows = data.filter((x) => x.name);
  const max = Math.max(...rows.map((x) => x.value), 1);
  const bh = Math.min(22, 190 / rows.length - 6);
  return `<svg class="svgc" viewBox="0 0 420 232" width="420" height="232">${rows.map((x, i) => {
    const y = 14 + i * (bh + 8);
    const w = (x.value / max) * 240;
    return `<text x="120" y="${y + bh / 2 + 4}" text-anchor="end">${esc(x.name)}</text><rect x="128" y="${y}" width="${Math.max(w, 0)}" height="${bh}" fill="${color}" rx="2"/><text x="${134 + Math.max(w, 0)}" y="${y + bh / 2 + 4}">${f.money(x.value)}</text>`;
  }).join('')}</svg>`;
}

export function budgetView(d, { scale = 1, chart = true } = {}) {
  const f = fmt(d.lang);
  const b = d.budget;
  const P = d.t.pack.budget;
  const kpi = [b.income, b.expenses, b.net, b.balance, b.pro, b.personal];
  const kpis = P.kpis.map((k, i) => `<tr><td class="bk-l">${esc(k)}</td><td class="bk-v" style="${i === 2 ? `color:${b.net < 0 ? C.loss : C.profit}` : ''}">${f.money(kpi[i])}</td></tr>`).join('');
  const cats = b.categories.map((c) => {
    const used = c.used === null ? '' : c.used > 1 ? `<span style="background:#FEE2E2;color:${C.loss};font-weight:700" class="pill">${f.pct0(c.used)}</span>`
      : c.used > 0.8 ? `<span style="background:#FEF3C7;color:${C.warn}" class="pill">${f.pct0(c.used)}</span>` : f.pct0(c.used);
    return `<tr><td>${esc(c.name)}</td><td class="r">${f.money(c.budget)}</td><td class="r">${f.money(c.spent)}</td><td class="r">${c.remaining === null ? '' : f.money(c.remaining)}</td><td class="r">${used}</td></tr>`;
  }).join('');
  const hist = b.history;
  const max = Math.max(...hist.flatMap((h) => [h.income, h.expenses]), 1);
  const top = niceTop(max);
  const chartSvg = `<svg class="svgc" viewBox="0 0 520 250" width="520" height="250">${[0, 0.25, 0.5, 0.75, 1].map((g) => `<line x1="44" x2="520" y1="${200 - 180 * g}" y2="${200 - 180 * g}" stroke="#E5E7EB"/><text x="38" y="${204 - 180 * g}" text-anchor="end">${f.int(top * g)}</text>`).join('')}
    ${hist.map((h, i) => {
      const x = 56 + i * 78;
      const bar = (v, dx, c) => (v > 0 ? `<rect x="${x + dx}" y="${200 - (v / top) * 180}" width="26" height="${(v / top) * 180}" fill="${c}" rx="2"/>` : '');
      return bar(h.income, 0, C.profit) + bar(h.expenses, 28, C.loss) + `<text x="${x + 27}" y="220" text-anchor="middle">${f.monthShort(h.d)}</text>`;
    }).join('')}
    <g transform="translate(170,236)"><rect width="10" height="10" fill="${C.profit}"/><text x="15" y="9">${esc(P.history[1])}</text><rect x="100" width="10" height="10" fill="${C.loss}"/><text x="115" y="9">${esc(P.history[2])}</text></g></svg>`;
  return `<div class="budget" style="zoom:${scale}">
    <div class="d-title">${esc(P.title)}</div>
    <div class="d-period"><b>${esc(P.month)}</b><span class="d-date wide">${f.monthLong(b.month)}</span></div>
    <div class="b-row"><table class="bk">${kpis}</table>
    <table class="bt"><tr>${P.table.map((h, i) => `<th class="${i ? 'r' : ''}">${esc(h)}</th>`).join('')}</tr>${cats}</table></div>
    ${chart ? `<div class="chart bchart"><div class="ct">${esc(P.chart)}</div>${chartSvg}</div>` : ''}</div>`;
}

export function pricingView(d, { scale = 1, scenarios = true, outputs = true, hl = [], side = false } = {}) {
  const f = fmt(d.lang);
  const p = d.t.pack.pricing;
  const pr = d.pricing;
  const PCT = [5, 7, 9, 10];
  const inputs = p.inputs.map((l, i) => `<tr><td class="pi-l">${esc(l)}</td><td class="pi-v">${PCT.includes(i) ? f.pct1(pr.inputs[i]) : f.money(pr.inputs[i])}</td></tr>`).join('');
  const out = (v, i) => (i === 1 ? f.pct1(v) : i === 8 ? f.roas(v) : i === 9 ? v : f.money(v));
  const outs = p.outputs.map((l, i) => `<tr class="${hl.includes(i) ? 'hl-row' : ''}"><td class="po-l"${i === 0 ? ' style="font-size:16px"' : ''}>${esc(l)}</td><td class="po-v" style="${i === 0 ? 'font-size:18px;' : ''}${(i === 0 || i === 7) ? `color:${pr.outputs[i] < 0 ? C.loss : C.profit}` : ''}">${out(pr.outputs[i], i)}</td></tr>`).join('');
  const stColor = pr.status === 'ok' ? ['#DCFCE7', C.profit] : pr.status === 'thin' ? ['#FEF3C7', C.warn] : ['#FEE2E2', C.loss];
  const sc = pr.scenarios.map((s) => `<tr class="${s.current ? 'cur' : ''}"><td class="r">${f.money(s.price)}</td><td class="r" style="color:${s.profit < 0 ? C.loss : C.profit}">${f.money(s.profit)}</td><td class="r">${f.pct1(s.margin)}</td></tr>`).join('');
  const scBlock = `<div class="${side ? 'sc-side' : ''}"><div class="sc-title">${esc(p.scenariosTitle)}</div><table class="psc"><tr>${p.scenarios.map((h) => `<th class="r">${esc(h)}</th>`).join('')}</tr>${sc}</table></div>`;
  return `<div class="pricing${side ? ' side' : ''}" style="zoom:${scale}">
    <div class="d-title">${esc(p.title)}</div>
    <div class="d-sub">${esc(p.subtitle)}</div>
    <div class="p-row"><table class="ptin"><tr><th colspan="2">${esc(p.inputsHeader)}</th></tr>${inputs}</table>
    ${outputs ? `<div><table class="pout"><tr><th colspan="2">${esc(p.outputsHeader)}</th></tr>${outs}</table>
    <div class="pstatus" style="background:${stColor[0]};color:${stColor[1]}">${esc(p.status[pr.status])}</div></div>` : ''}
    ${scenarios && side ? scBlock : ''}</div>
    ${scenarios && !side ? scBlock : ''}
  </div>`;
}

// Mobile Google Sheets (phone screen content)
export function mobileSheet({ title, gridHtml, tabs, active }) {
  return `<div class="m-app"><div class="m-top"><span class="m-back">✓</span><span class="m-title">${esc(title)}</span><span class="m-ico">⋮</span></div>
  <div class="m-fx"><span>fx</span></div><div class="m-grid">${gridHtml}</div>
  <div class="m-tabs">${tabs.map(([k, n]) => `<span class="${k === active ? 'on' : ''}" style="--tc:${TAB_COLOR(k)}">${esc(n)}</span>`).join('')}</div></div>`;
}

// ---------------------------------------------------------------------------
// CSS
// ---------------------------------------------------------------------------

const BASE_CSS = `
.browser{color:#0F172A;background:#fff;border-radius:14px;overflow:hidden;box-shadow:0 30px 80px rgba(2,6,23,.45),0 0 0 1px rgba(15,23,42,.08);display:flex;flex-direction:column}
.b-bar{height:40px;background:#EEF1F5;display:flex;align-items:center;gap:8px;padding:0 16px;flex:none;border-bottom:1px solid #DDE2E8}
.dot{width:12px;height:12px;border-radius:50%}
.b-url{margin-left:18px;background:#fff;border-radius:8px;height:26px;flex:1;max-width:520px;display:flex;align-items:center;padding:0 12px;font-size:12.5px;color:#475569}
.b-body{flex:1;overflow:hidden;position:relative}
.gs{display:flex;flex-direction:column;height:100%;background:#fff}
.gs-top{display:flex;align-items:center;gap:12px;padding:8px 16px 4px;flex:none}
.gs-icon{width:26px;height:34px;background:#0F9D58;border-radius:3px;position:relative;flex:none}
.gs-icon div{position:absolute;inset:11px 6px 7px;border:2px solid #fff;border-radius:1px;background:linear-gradient(#fff,#fff) center/2px 100% no-repeat,linear-gradient(#fff,#fff) center/100% 2px no-repeat}
.gs-title{font-size:17px;color:#1F2937}
.gs-star{color:#94A3B8;font-size:15px}
.gs-menu{display:flex;gap:14px;font-size:13px;color:#374151;margin-top:2px}
.gs-share{margin-left:auto;background:#C2E7FF;color:#001D35;font-weight:600;font-size:13.5px;padding:8px 20px;border-radius:18px}
.gs-fx{display:flex;align-items:center;gap:10px;height:30px;border-top:1px solid #E1E3E6;border-bottom:1px solid #E1E3E6;margin-top:6px;padding:0 12px;font-size:12.5px;color:#475569;flex:none;background:#F9FBFD}
.gs-cell{width:60px;border-right:1px solid #E1E3E6}
.gs-fxi{color:#94A3B8;font-style:italic}
.gs-grid{flex:1;overflow:hidden;position:relative;background:#fff}
.gs-tabs{height:38px;flex:none;background:#F9FBFD;border-top:1px solid #E1E3E6;display:flex;align-items:stretch;gap:2px;padding:0 10px;font-size:13px;color:#3C4043;white-space:nowrap;overflow:hidden}
.gs-tabicon{display:flex;align-items:center;padding:0 10px;color:#5F6368;font-size:16px}
.gs-tab{display:flex;align-items:center;padding:0 14px;border-bottom:3px solid var(--tc);margin-bottom:0}
.gs-tab.on{background:#E1F0E6;background:#fff;font-weight:600;color:#0B57D0;box-shadow:inset 0 1px 0 #E1E3E6}
table.g{border-collapse:collapse;table-layout:fixed;font-size:13px;color:${C.ink}}
table.g td,table.g th{border:1px solid #E2E3E3;padding:0 7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:400}
.g-letters th{height:22px;background:#F8F9FA;color:#5F6368;font-size:11.5px;font-weight:500!important;text-align:center}
.g-corner{background:#F8F9FA}
td.g-num{background:#F8F9FA;color:#5F6368;font-size:11.5px;text-align:center;padding:0!important}
td.g-h{background:${C.ink};color:#fff;font-weight:700!important;white-space:normal!important;line-height:1.2;vertical-align:middle}
td.g-h.auto{background:${C.primary};color:${C.ink}}
table.g td.r{text-align:right}
table.g td.c{text-align:center}
table.g tr.strike td:not(.g-num){color:#94A3B8;text-decoration:line-through}
table.g tr.dim td:not(.g-num){opacity:.45}
table.g tr.bold td{font-weight:700}
.tab{font-variant-numeric:tabular-nums}
.hl-col{box-shadow:inset 3px 0 0 ${C.primary},inset -3px 0 0 ${C.primary}}
.dash,.budget,.pricing{background:${C.bg};padding:10px 0 20px 24px;font-size:13px;min-height:100%}
.d-title{font-size:26px;font-weight:700;height:48px;display:flex;align-items:center}
.d-sub{color:${C.muted};margin:2px 0 14px}
.d-period{display:flex;align-items:center;gap:10px;margin-bottom:16px}
.d-period i{color:${C.muted}}
.d-date{width:110px;height:24px;background:${C.primarySoft};border:1px solid ${C.primary}}
.d-date.wide{width:auto;padding:0 10px;display:flex;align-items:center;font-weight:500}
.tiles{display:grid;grid-template-columns:repeat(4,236px);gap:12px 0;width:944px}
.tile{background:#fff;border:1px solid ${C.border};height:68px;padding:8px 12px 6px;display:flex;flex-direction:column;justify-content:space-between;margin-right:0}
.tile.pk{background:#fff;border-color:#D9F99D}
.tl{color:${C.muted};font-size:12.5px}
.tv{font-size:23px;font-weight:700;font-variant-numeric:tabular-nums}
.charts{display:grid;grid-template-columns:472px 472px;gap:16px 0;margin-top:22px}
.chart{background:#fff;border:1px solid ${C.border};width:458px;padding:10px 14px}
.ct{font-size:14px;font-weight:600;color:#334155;margin-bottom:4px}
.svgc{display:block;font-family:Inter;font-size:11px;fill:#475569;max-width:100%}
.bchart{width:560px;margin-top:22px}
.b-row{display:flex;gap:32px;align-items:flex-start}
table.bk,table.bt,table.ptin,table.pout,table.psc{border-collapse:collapse;background:#fff;font-variant-numeric:tabular-nums}
table.bk td{border:1px solid ${C.border};padding:8px 12px}
.bk-l{color:${C.muted};width:220px}
.bk-v{font-weight:700;font-size:15px;text-align:right;width:120px}
table.bt th{background:${C.primary};color:${C.ink};padding:10px 12px;font-weight:700;text-align:left}
table.bt td{border:1px solid ${C.border};padding:6px 12px;height:30px}
th.r,td.r{text-align:right!important}
.pill{padding:2px 8px;border-radius:4px}
.p-row{display:flex;gap:28px;align-items:flex-start}
table.ptin th,table.pout th{background:${C.ink};color:#fff;text-align:left;padding:10px 12px;font-weight:700}
table.pout th{background:${C.primary};color:${C.ink}}
table.ptin td,table.pout td{padding:4px 12px;height:28px}
.pi-l{width:270px;border-bottom:1px solid #F1F5F9}
.pi-v{width:120px;background:${C.primarySoft};border:1px solid ${C.primary};font-weight:700;text-align:right}
.po-l{width:300px;border-bottom:1px solid ${C.border};border-left:1px solid ${C.border}}
.po-v{width:130px;font-weight:700;text-align:right;border-bottom:1px solid ${C.border};border-right:1px solid ${C.border}}
tr.hl-row td{background:${C.primarySoft};box-shadow:inset 0 2px 0 ${C.primary},inset 0 -2px 0 ${C.primary}}
.pstatus{margin-top:14px;padding:10px 14px;font-weight:700;font-size:15px;width:430px}
.sc-title{font-weight:700;font-size:16px;margin:22px 0 8px}
.sc-side .sc-title{margin-top:0}
.pricing.side table.psc th{width:130px;white-space:normal}
table.psc th{background:${C.primary};color:${C.ink};padding:10px 14px;font-weight:700;width:190px}
table.psc td{border:1px solid ${C.border};padding:6px 14px;height:30px}
table.psc tr.cur td{background:${C.primarySoft};font-weight:700}
.phone{color:#0F172A;background:#0B0F19;border-radius:62px;padding:14px;box-shadow:0 40px 90px rgba(2,6,23,.5),inset 0 0 0 2px #2A3142}
.ph-screen{border-radius:48px;overflow:hidden;background:#fff;position:relative;display:flex;flex-direction:column}
.ph-status{height:50px;display:flex;align-items:center;justify-content:space-between;padding:6px 30px 0;font-weight:600;font-size:15px;flex:none}
.ph-notch{width:120px;height:34px;background:#0B0F19;border-radius:20px}
.m-app{display:flex;flex-direction:column;flex:1;min-height:0}
.m-top{display:flex;align-items:center;gap:14px;padding:8px 16px;font-size:17px;flex:none}
.m-back{color:#0F9D58;font-weight:700;font-size:20px}
.m-title{font-weight:600;flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.m-fx{height:34px;border-top:1px solid #E1E3E6;border-bottom:1px solid #E1E3E6;display:flex;align-items:center;padding:0 14px;color:#94A3B8;font-style:italic;flex:none}
.m-grid{flex:1;overflow:hidden}
.m-tabs{flex:none;height:48px;border-top:1px solid #E1E3E6;display:flex;gap:4px;padding:0 8px 0;align-items:stretch;font-size:14px;white-space:nowrap;overflow:hidden;background:#F9FBFD;margin-bottom:22px}
.m-tabs span{display:flex;align-items:center;padding:0 12px;border-bottom:3px solid var(--tc)}
.m-tabs span.on{font-weight:700;color:#0B57D0;background:#fff}
`;
